INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('CATAMARCA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('CHACO', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('CHUBUT', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('CORDOBA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('CORRIENTES', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('ENTRE RIOS', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('FORMOSA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('JUJUY', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('LA PAMPA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('LA RIOJA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('MENDOZA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('MISIONES', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('NEUQUÉN', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('RIO NEGRO', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('SALTA', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('SAN JUÁN', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('SANTA CRUZ', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('SANTA FE', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('SANTIAGO DEL ESTERO', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('TIERRA DEL FUEGO', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('TUCUMÁN', 1);
INSERT INTO herramientas.provincia (descripcion, pais) VALUES ('Capital Federal', 1);